### ISSUE TITLE
社交媒体的logo 和 超链接更改

### ISSUE THREAD

**Issue by zenwan** [TriDiamond/hexo-theme-obsidian#34]
国内用户基本没有twitter、stack-overflow 账户
可以更改为 知乎、微博、微信、邮箱等不？

**Comment by PSheon** [comment]
嗨，目前的圖示已經寫死無法直接新增
要換圖示需要 [訂製](https://www.iconfont.cn/) 並下載你自己的圖庫，最後新增樣式規則，會類似以下
```css
.icon-linkedin:before {
  content: "\e747";
}
.icon-email:before {
  content: "\e62e";
}
```
成果
![image](https://user-images.githubusercontent.com/20603727/70417623-a4c7cf80-1a9c-11ea-8c77-5bac22cf1162.png)
