### ISSUE TITLE
How can I change the language?

### ISSUE THREAD

**Issue by jadelike-wine** [TriDiamond/hexo-theme-obsidian#4]
How can I change the language?

**Comment by TriDiamond** [comment]
@jadelike-wine 
Change your language setting to `en` or leave it empty in Hexo's config file `_config.yml`

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 三·钻 TriDiamond
subtitle:
description:
keywords:
author: 三·钻 TriDiamond
language:
timezone:
```
