### ISSUE TITLE
在添加了categories页面和tags页面之后主页右上角菜单栏没有出现选项

### ISSUE THREAD

**Issue by Sicmatr1x** [TriDiamond/hexo-theme-obsidian#7]

**Comment by TriDiamond** [comment]
首页的菜单是要在主题的配置文件`_config.yml`文件里面配置的。

加入如下配置就可以显示了
```yml
# Menu setting | format = title_name: link_url
menu:
  CATEGORIES: /categories
  TAGS: /tags
```
