### ISSUE TITLE
gitee部署后 logo图片 点击后无法 导航到首页

### ISSUE THREAD

**Issue by Proud-Li** [TriDiamond/hexo-theme-obsidian#74]
logo点击后 跳转网址 变了
这应该 是gitee的目录 环境问题 发来问问 如何兼容修改

链接
http://cloud_c2.gitee.io/blog/

**Comment by TriDiamond** [comment]
![image](https://user-images.githubusercontent.com/24708758/77329713-55f72a80-6d59-11ea-9022-90946b86766d.png)
我这里点击没有问题，我用的是谷歌浏览器，你用的是？

**Comment by Proud-Li** [comment]
我刚刚 把index 改掉了 所以可以了
<a class="image-logo" href="/blog/"></a>
链接加了 1层目录 blog/

**Comment by Flexiston** [comment]
还有一个办法，根目录 `_config.yml` 里有个配置：
```yaml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks
```
把 `root` 设置成 `/blog` 就可以了
