### ISSUE TITLE
遇到几个问题

### ISSUE THREAD

**Issue by Flexiston** [TriDiamond/hexo-theme-obsidian#76]
#### 1. 设置中文无效

配置文件如下：
``` yml
# Site
title: Andy1246's Blog
subtitle: ''
description: ''
keywords:
author: Andy1246
language: zh-CN
timezone: ''
```
[![英文菜单](https://i.postimg.cc/J49JJftS/capture-20200323205329318.png)](https://postimg.cc/SJfJbt6G)

#### 2. `CATEGORIES`页面和`TAGS`页面点击出现 _404_

![404](https://i.postimg.cc/sgyqVNsC/capture-20200323204747704.png)

#### 4. 请问`搜索`要怎么设置？

[![无搜索图标](https://i.postimg.cc/J49JJftS/capture-20200323205329318.png)](https://postimg.cc/SJfJbt6G)

#### 6. 网站`logo`文字怎么生成？

<br />

 **附博客地址：https://andy1246.github.io**
